name: QMS issue
description: Insert a new issue through the QMS form
labels: ["Priority: Medium", "Status: Discussion", "Type: Question", "bug"]
body:
  - type: markdown
    attributes:
      value: "## Form instructions"
  - type: markdown
    attributes:
      value: |
        Fill this informations:
        - title
        - type
        - description
        - assignees
        
        Check labels before submit.
  - type: dropdown
    id: issue-type
    attributes:
      label: Type
      description: Select the kind of issue
      options:
        - Enhancement
        - Bug
        - Question
        - Refactor
      # default: 0
    validations:
      required: true
  - type: textarea
    id: issue-description
    attributes:
      label: Description
      description: Add a description
    validations:
      required: true
