name: Question
description: Insert a new question issue through the QMS form
labels: ["Priority: Medium", "Status: Discussion", "Type: Question"]
body:
  - type: markdown
    attributes:
      value: "## Form instructions"
  - type: markdown
    attributes:
      value: |
        Remember to assigne the issue and check Priority label.
  - type: textarea
    id: issue-description
    attributes:
      label: Description
      description: Add a description
    validations:
      required: true
