name: Refactor
description: Insert a new refactor issue through the QMS form
labels: ["Priority: Medium", "Status: Discussion", "Type: Refactor"]
body:
  - type: markdown
    attributes:
      value: "## Form instructions"
  - type: markdown
    attributes:
      value: |
        Fill this informations:
        - Title
        - Description
        - Assignees
        - Priority label
  - type: textarea
    id: issue-description
    attributes:
      label: Description
      description: Add a description
    validations:
      required: true
